// components/navbar/Navbar.tsx
import { Button } from "@/components/ui/button";
import {
    NavigationMenu,
    NavigationMenuContent,
    NavigationMenuItem,
    NavigationMenuLink,
    NavigationMenuList,
    NavigationMenuTrigger,
} from "@/components/ui/navigation-menu";
import { Icon } from "@iconify-icon/react";
import Image from "next/image";
import Link from "next/link";
import { useLocalStorage } from "usehooks-ts";

import { type FC, type ReactNode, useEffect, useState } from "react";
import { AnimatedArrow } from "../decorations/AnimatedArrow";
import {
    Accordion,
    AccordionContent,
    AccordionItem,
    AccordionTrigger,
} from "../ui/accordion";
import {
    Drawer,
    DrawerContent,
    DrawerHeader,
    DrawerTitle,
    DrawerTrigger,
} from "../ui/drawer";
import { NewsBar } from "./NewsBar";
import { ProductItem, type ProductItemProps } from "./ProductItem";

/**
 * Product information for the navigation menu
 */
const products: ProductItemProps[] = [
    {
        name: "Lysand",
        description:
            "Highly standardized federation protocol that's easy to use and understand.",
        icon: "tabler:world-www",
        href: "https://lysand.org",
    },
    {
        name: "Lysand Server",
        description:
            "Reference implementation of the Lysand protocol. Fast, lightweight and configurable.",
        icon: "tabler:server",
        href: "https://github.com/lysand-org/lysand",
    },
    {
        name: "Join Mastodon",
        description:
            "A landing page for mastodon.de, a social media with no ads, no tracking, and no algorithms. Made with Nuxt.js and Tailwind CSS.",
        icon: "tabler:brand-mastodon",
        href: "https://join-mastodon.de",
    },
    {
        name: "KitsuLife",
        description:
            "Website for the Kitsu service suite, showcasing features and the community for Kitsu.",
        icon: "tabler:social",
        href: "https://kitsu.life",
    },
];

/**
 * Current news information
 */
const currentNews = {
    id: "lysand3",
    title: "Lysand 3.0",
    description: "Lysand 3.0 is now available!",
    linkText: "Read the docs",
    href: "https://lysand.org",
};

/**
 * Navbar component
 */
export const Navbar: FC = () => {
    const [isOpen, setIsOpen] = useState(false);
    const [closedNews, setClosedNews] = useLocalStorage<string[]>(
        "closedNews",
        [],
    );
    const [hasLocalStorageLoaded, setHasLocalStorageLoaded] = useState(false);

    useEffect(() => {
        setHasLocalStorageLoaded(true);
    }, []);

    return (
        <header className="z-10 bg-background/30 backdrop-blur-lg fixed top-0 inset-x-0">
            <NewsBar
                news={currentNews}
                closedNews={closedNews}
                setClosedNews={setClosedNews}
                hasLocalStorageLoaded={hasLocalStorageLoaded}
            />
            <nav className="container flex items-center justify-between p-6">
                <div className="flex lg:flex-1">
                    <Link href="/" className="-m-1.5 p-1.5">
                        <span className="sr-only">CPlusPatch</span>
                        <Image
                            className="h-8 w-auto"
                            src="/images/icons/logo.svg"
                            alt="CPlusPatch Logo"
                            width={229}
                            height={229}
                        />
                    </Link>
                </div>
                <div className="flex lg:hidden">
                    <MobileMenu
                        isOpen={isOpen}
                        setIsOpen={setIsOpen}
                        products={products}
                    >
                        <Button
                            variant="ghost"
                            size="icon"
                            className="-m-2.5 inline-flex items-center justify-center rounded-md p-2.5 text-foreground"
                            onClick={() => setIsOpen(true)}
                        >
                            <span className="sr-only">Open main menu</span>
                            <Icon
                                icon="tabler:menu-2"
                                className="size-6"
                                aria-hidden="true"
                                width="none"
                            />
                        </Button>
                    </MobileMenu>
                </div>
                <NavigationMenu className="hidden lg:flex lg:gap-x-12">
                    <NavigationMenuList>
                        <NavigationMenuItem>
                            <NavigationMenuTrigger className="text-sm !bg-transparent font-semibold leading-6 text-foreground">
                                Projects
                            </NavigationMenuTrigger>
                            <NavigationMenuContent>
                                <ul className="grid w-[400px] gap-3 p-4 md:w-[500px] md:grid-cols-3 grid-rows-2 lg:w-[800px]">
                                    <NavigationMenuLink asChild={true}>
                                        <Link
                                            className="flex h-full w-full col-start-1 row-span-full select-none flex-col justify-end rounded-md bg-gradient-to-b from-muted/50 to-muted p-6 no-underline outline-none focus:shadow-md"
                                            href="/"
                                        >
                                            <Icon
                                                icon="tabler:charts"
                                                className="size-6"
                                                width="none"
                                            />
                                            <div className="mb-2 mt-4 text-lg font-medium">
                                                CPlusPatch
                                            </div>
                                            <p className="text-sm leading-tight text-muted-foreground">
                                                Designed for simplicity. Built
                                                for performance. Made for you.
                                            </p>
                                        </Link>
                                    </NavigationMenuLink>
                                    {products.map((product) => (
                                        <li
                                            key={product.name}
                                            className="[&:nth-child(2n)]:col-start-2 [&:nth-child(2n+1)]:col-start-3"
                                        >
                                            <ProductItem {...product} />
                                        </li>
                                    ))}
                                </ul>
                            </NavigationMenuContent>
                        </NavigationMenuItem>
                        <NavigationMenuItem>
                            <Link
                                href="/blog"
                                legacyBehavior={true}
                                passHref={true}
                            >
                                <NavigationMenuLink className="text-sm font-semibold leading-6 text-foreground">
                                    Blog
                                </NavigationMenuLink>
                            </Link>
                        </NavigationMenuItem>
                        <NavigationMenuItem>
                            <Link
                                href="/contact"
                                legacyBehavior={true}
                                passHref={true}
                            >
                                <NavigationMenuLink className="text-sm font-semibold leading-6 text-foreground">
                                    Contact
                                </NavigationMenuLink>
                            </Link>
                        </NavigationMenuItem>
                    </NavigationMenuList>
                </NavigationMenu>
                <div className="hidden lg:flex lg:flex-1 lg:justify-end">
                    <Link
                        href="https://github.com/cpluspatch/web-landing"
                        target="_blank"
                        className="text-sm font-semibold group leading-6 text-foreground flex items-center"
                    >
                        Source Code
                        <AnimatedArrow />
                    </Link>
                </div>
            </nav>
        </header>
    );
};

/**
 * Mobile menu component
 */
const MobileMenu: FC<{
    isOpen: boolean;
    setIsOpen: (isOpen: boolean) => void;
    products: ProductItemProps[];
    children: ReactNode;
}> = ({ isOpen, setIsOpen, products, children }) => (
    <Drawer open={isOpen} onOpenChange={setIsOpen}>
        <DrawerTrigger asChild={true}>{children}</DrawerTrigger>
        <DrawerContent>
            <div className="max-w-xl w-full mx-auto">
                <DrawerHeader>
                    <DrawerTitle>
                        <Link
                            href="/"
                            className="px-2"
                            onClick={() => setIsOpen(false)}
                        >
                            <span className="sr-only">CPlusPatch</span>
                            <Image
                                className="h-8 w-auto"
                                src="/images/icons/logo.svg"
                                alt="CPlusPatch Logo"
                                width={229}
                                height={229}
                            />
                        </Link>
                    </DrawerTitle>
                </DrawerHeader>
                <div className="p-4">
                    <div className="flex flex-col gap-y-4">
                        <Accordion type="single" collapsible={true}>
                            <AccordionItem value="item-1">
                                <Button
                                    variant="outline"
                                    className="w-full"
                                    asChild={true}
                                >
                                    <AccordionTrigger>
                                        Projects
                                    </AccordionTrigger>
                                </Button>
                                <AccordionContent className="py-4">
                                    <ul className="space-y-2">
                                        {products.map((product) => (
                                            <li key={product.name}>
                                                <ProductItem
                                                    {...product}
                                                    onClick={() =>
                                                        setIsOpen(false)
                                                    }
                                                />
                                            </li>
                                        ))}
                                    </ul>
                                </AccordionContent>
                            </AccordionItem>
                        </Accordion>
                        <Link href="/blog" onClick={() => setIsOpen(false)}>
                            <Button variant="outline" className="w-full">
                                Blog
                            </Button>
                        </Link>
                        <Link href="/contact" onClick={() => setIsOpen(false)}>
                            <Button variant="outline" className="w-full">
                                Contact
                            </Button>
                        </Link>
                        <Link
                            href="https://github.com/cpluspatch/web-landing"
                            target="_blank"
                            onClick={() => setIsOpen(false)}
                        >
                            <Button variant="outline" className="w-full">
                                Source Code
                            </Button>
                        </Link>
                    </div>
                </div>
            </div>
        </DrawerContent>
    </Drawer>
);

// components/headers/Navbar.vue
<script setup lang="ts">
const products = [
    {
        name: "Versia",
        description:
            "Highly standardized federation protocol that's easy to use and understand.",
        icon: "tabler:world-www",
        href: "https://versia.pub",
    },
    {
        name: "Versia Server",
        description:
            "Reference implementation of the Versia protocol. Fast, lightweight and configurable.",
        icon: "tabler:server",
        href: "https://github.com/versia-pub/server",
    },
    {
        name: "Join Mastodon",
        description:
            "A landing page for mastodon.de, a social media with no ads, no tracking, and no algorithms. Made with Nuxt.js and Tailwind CSS.",
        icon: "tabler:brand-mastodon",
        href: "https://join-mastodon.de",
    },
    {
        name: "KitsuLife",
        description:
            "Website for the Kitsu service suite, showcasing features and the community for Kitsu.",
        icon: "tabler:social",
        href: "https://kitsu.life",
    },
];

const currentNews = {
    id: "versia5",
    title: "Versia 0.5",
    description: "Versia 0.5 is now available!",
    linkText: "Read the docs",
    href: "https://versia.pub",
};

const open = ref(false);
const closedNews = useLocalStorage<string[]>("closedNews", []);

const hasLocalStorageLoaded = ref(false);

onMounted(() => {
    hasLocalStorageLoaded.value = true;
});
</script>
<template>
    <header data-phys="true" :class="[
        'z-10 backdrop-blur-lg fixed top-0 inset-x-0 bg-dark-800/30',
    ]">
        <div v-if="!closedNews.includes(currentNews.id) && hasLocalStorageLoaded"
            class="relative isolate flex items-center gap-x-6 overflow-hidden bg-dark-900 px-6 py-2.5 sm:px-3.5 sm:before:flex-1">
            <div class="flex flex-wrap justify-center gap-x-4 gap-y-2 w-full">
                <p class="text-sm text-gray-50">
                    <strong class="font-semibold">{{
                        currentNews.title
                        }}</strong>&nbsp;•&nbsp;{{ currentNews.description }}
                </p>
                <a :href="currentNews.href" target="_blank" class="text-sm font-semibold text-gray-50 group">{{
                    currentNews.linkText }}
                    <ButtonsAnimatedArrow />
                </a>
            </div>
            <div class="flex justify-end">
                <button type="button" class="-m-3 p-3 focus-visible:outline-offset-[-4px]"
                    @click="closedNews.push(currentNews.id)">
                    <span class="sr-only">Dismiss</span>
                    <iconify-icon icon="tabler:x" height="none" class="size-5 text-gray-50" aria-hidden="true" />
                </button>
            </div>
        </div>
        <nav class="mx-auto flex max-w-7xl items-center justify-between p-6 lg:px-8">
            <div class="flex lg:flex-1">
                <NuxtLink href="/" class="-m-1.5 p-1.5">
                    <span class="sr-only">CPlusPatch</span>
                    <nuxt-img class="h-8 w-auto" width="229" height="229" src="/images/icons/logo.svg"
                        alt="CPlusPatch Logo" />
                </NuxtLink>
            </div>
            <div class="flex lg:hidden">
                <button type="button"
                    class="-m-2.5 inline-flex items-center justify-center rounded-md p-2.5 text-gray-200"
                    @click="open = true">
                    <span class="sr-only">Open main menu</span>
                    <iconify-icon icon="tabler:menu-2" height="none" class="size-6" aria-hidden="true" />
                </button>
            </div>
            <HeadlessPopoverGroup class="hidden lg:flex lg:gap-x-12">
                <HeadlessPopover>
                    <HeadlessPopoverButton id="thebutton"
                        class="flex items-center gap-x-1 text-sm font-semibold leading-6 text-gray-50">
                        Projects
                        <iconify-icon icon="tabler:chevron-down" height="none" class="size-5 flex-none text-gray-500"
                            aria-hidden="true" />
                    </HeadlessPopoverButton>

                    <transition enter-active-class="transition ease-out duration-200"
                        enter-from-class="opacity-0 -translate-y-1" enter-to-class="opacity-100 translate-y-0"
                        leave-active-class="transition ease-in duration-150"
                        leave-from-class="opacity-100 translate-y-0" leave-to-class="opacity-0 -translate-y-1">
                        <HeadlessPopoverPanel
                            class="absolute inset-x-0 top-0 -z-10 bg-dark-700 pt-14 shadow-lg ring-1 ring-dark-900/5">
                            <div class="mx-auto grid max-w-7xl grid-cols-4 gap-x-4 px-6 py-10 lg:px-8 xl:gap-x-8">
                                <div v-for="item in products" :key="item.name"
                                    class="group relative rounded-lg p-6 text-sm leading-6 hover:bg-dark-400 duration-200 ring-dark-200 hover:ring-1">
                                    <div
                                        class="flex size-11 items-center justify-center rounded-lg bg-dark-300 duration-200 group-hover:bg-dark-700">
                                        <iconify-icon :icon="item.icon" height="none"
                                            class="size-6 text-gray-400 group-hover:text-orange-400"
                                            aria-hidden="true" />
                                    </div>
                                    <a target="_blank" :href="item.href" class="mt-6 block font-semibold text-gray-50">
                                        {{ item.name }}
                                        <span class="absolute inset-0" />
                                    </a>
                                    <p class="mt-1 text-gray-300">
                                        {{ item.description }}
                                    </p>
                                </div>
                            </div>
                        </HeadlessPopoverPanel>
                    </transition>
                </HeadlessPopover>

                <NuxtLink href="/blog" class="text-sm font-semibold leading-6 text-gray-50">Blog</NuxtLink>

                <NuxtLink href="/contact" class="text-sm font-semibold leading-6 text-gray-50">Contact</NuxtLink>
            </HeadlessPopoverGroup>
            <div class="hidden lg:flex lg:flex-1 lg:justify-end">
                <a target="_blank" href="https://github.com/cpluspatch/web-landing"
                    class="text-sm font-semibold group leading-6 text-gray-50">Source Code
                    <ButtonsAnimatedArrow />
                </a>
            </div>
        </nav>
        <HeadlessDialog as="div" class="lg:hidden" :open="open" @close="open = false">
            <div class="fixed inset-0 z-10"></div>
            <HeadlessDialogPanel
                class="fixed inset-y-0 right-0 z-10 w-full overflow-y-auto bg-dark-700 px-6 py-6 sm:max-w-sm sm:ring-1 sm:ring-dark-50/10">
                <div class="flex items-center justify-between">
                    <NuxtLink href="/" class="-m-1.5 p-1.5">
                        <span class="sr-only">CPlusPatch</span>
                        <nuxt-img class="h-8 w-auto" width="229" height="229" src="/images/icons/logo.svg"
                            alt="CPlusPatch Logo" />
                    </NuxtLink>
                    <button type="button" class="-m-2.5 rounded-md p-2.5 text-gray-200" @click="open = false">
                        <span class="sr-only">Close menu</span>
                        <iconify-icon icon="tabler:x" height="none" class="size-6" aria-hidden="true" />
                    </button>
                </div>
                <div class="mt-6 flow-root">
                    <div class="-my-6 divide-y divide-gray-400/10">
                        <div class="space-y-2 py-6">
                            <HeadlessDisclosure v-slot="{ open }" as="div" class="-mx-3">
                                <HeadlessDisclosureButton
                                    class="flex w-full items-center justify-between rounded-lg py-2 pl-3 pr-3.5 text-base font-semibold leading-7 text-gray-50 hover:bg-dark-500">
                                    Projects
                                    <iconify-icon icon="tabler:chevron-down" height="none" :class="[
                                        open ? '-scale-y-100' : '',
                                        'size-5 flex-none duration-200',
                                    ]" aria-hidden="true" />
                                </HeadlessDisclosureButton>
                                <HeadlessDisclosurePanel class="mt-2 space-y-2">
                                    <HeadlessDisclosureButton v-for="item in [...products]" :key="item.name" as="a"
                                        :href="item.href"
                                        class="block rounded-lg py-2 pl-6 pr-3 text-sm font-semibold leading-7 text-gray-50 hover:bg-dark-300">
                                        {{
                                            item.name
                                        }}</HeadlessDisclosureButton>
                                </HeadlessDisclosurePanel>
                            </HeadlessDisclosure>
                            <NuxtLink href="/blog"
                                class="-mx-3 block rounded-lg px-3 py-2 text-base font-semibold leading-7 text-gray-50 hover:bg-dark-500">
                                Blog</NuxtLink>
                            <NuxtLink href="/contact"
                                class="-mx-3 block rounded-lg px-3 py-2 text-base font-semibold leading-7 text-gray-50 hover:bg-dark-500">
                                Contact</NuxtLink>
                        </div>
                        <div class="py-6">
                            <a target="_blank" href="https://github.com/cpluspatch/web-landing"
                                class="-mx-3 block rounded-lg px-3 py-2.5 text-base font-semibold leading-7 text-gray-50 hover:bg-dark-500">Source
                                Code</a>
                        </div>
                    </div>
                </div>
            </HeadlessDialogPanel>
        </HeadlessDialog>
    </header>
</template>
