// components/navbar/Navbar.tsx
import { Button } from "@/components/ui/button";
import {
    NavigationMenu,
    NavigationMenuContent,
    NavigationMenuItem,
    NavigationMenuLink,
    NavigationMenuList,
    NavigationMenuTrigger,
} from "@/components/ui/navigation-menu";
import { Icon } from "@iconify-icon/react";
import Image from "next/image";
import Link from "next/link";
import { useLocalStorage } from "usehooks-ts";

import { type FC, type ReactNode, useEffect, useState } from "react";
import { AnimatedArrow } from "../decorations/AnimatedArrow";
import {
    Accordion,
    AccordionContent,
    AccordionItem,
    AccordionTrigger,
} from "../ui/accordion";
import {
    Drawer,
    DrawerContent,
    DrawerHeader,
    DrawerTitle,
    DrawerTrigger,
} from "../ui/drawer";
import { NewsBar } from "./NewsBar";
import { ProductItem, type ProductItemProps } from "./ProductItem";

/**
 * Product information for the navigation menu
 */
const products: ProductItemProps[] = [
    {
        name: "Lysand",
        description:
            "Highly standardized federation protocol that's easy to use and understand.",
        icon: "tabler:world-www",
        href: "https://lysand.org",
    },
    {
        name: "Lysand Server",
        description:
            "Reference implementation of the Lysand protocol. Fast, lightweight and configurable.",
        icon: "tabler:server",
        href: "https://github.com/lysand-org/lysand",
    },
    {
        name: "Join Mastodon",
        description:
            "A landing page for mastodon.de, a social media with no ads, no tracking, and no algorithms. Made with Nuxt.js and Tailwind CSS.",
        icon: "tabler:brand-mastodon",
        href: "https://join-mastodon.de",
    },
    {
        name: "KitsuLife",
        description:
            "Website for the Kitsu service suite, showcasing features and the community for Kitsu.",
        icon: "tabler:social",
        href: "https://kitsu.life",
    },
];

/**
 * Current news information
 */
const currentNews = {
    id: "lysand3",
    title: "Lysand 3.0",
    description: "Lysand 3.0 is now available!",
    linkText: "Read the docs",
    href: "https://lysand.org",
};

/**
 * Navbar component
 */
export const Navbar: FC = () => {
    const [isOpen, setIsOpen] = useState(false);
    const [closedNews, setClosedNews] = useLocalStorage<string[]>(
        "closedNews",
        [],
    );
    const [hasLocalStorageLoaded, setHasLocalStorageLoaded] = useState(false);

    useEffect(() => {
        setHasLocalStorageLoaded(true);
    }, []);

    return (
        <header className="z-10 bg-background/30 backdrop-blur-lg fixed top-0 inset-x-0">
            <NewsBar
                news={currentNews}
                closedNews={closedNews}
                setClosedNews={setClosedNews}
                hasLocalStorageLoaded={hasLocalStorageLoaded}
            />
            <nav className="container flex items-center justify-between p-6">
                <div className="flex lg:flex-1">
                    <Link href="/" className="-m-1.5 p-1.5">
                        <span className="sr-only">CPlusPatch</span>
                        <Image
                            className="h-8 w-auto"
                            src="/images/icons/logo.svg"
                            alt="CPlusPatch Logo"
                            width={229}
                            height={229}
                        />
                    </Link>
                </div>
                <div className="flex lg:hidden">
                    <MobileMenu
                        isOpen={isOpen}
                        setIsOpen={setIsOpen}
                        products={products}
                    >
                        <Button
                            variant="ghost"
                            size="icon"
                            className="-m-2.5 inline-flex items-center justify-center rounded-md p-2.5 text-foreground"
                            onClick={() => setIsOpen(true)}
                        >
                            <span className="sr-only">Open main menu</span>
                            <Icon
                                icon="tabler:menu-2"
                                className="size-6"
                                aria-hidden="true"
                                width="none"
                            />
                        </Button>
                    </MobileMenu>
                </div>
                <NavigationMenu className="hidden lg:flex lg:gap-x-12">
                    <NavigationMenuList>
                        <NavigationMenuItem>
                            <NavigationMenuTrigger className="text-sm !bg-transparent font-semibold leading-6 text-foreground">
                                Projects
                            </NavigationMenuTrigger>
                            <NavigationMenuContent>
                                <ul className="grid w-[400px] gap-3 p-4 md:w-[500px] md:grid-cols-3 grid-rows-2 lg:w-[800px]">
                                    <NavigationMenuLink asChild={true}>
                                        <Link
                                            className="flex h-full w-full col-start-1 row-span-full select-none flex-col justify-end rounded-md bg-gradient-to-b from-muted/50 to-muted p-6 no-underline outline-none focus:shadow-md"
                                            href="/"
                                        >
                                            <Icon
                                                icon="tabler:charts"
                                                className="size-6"
                                                width="none"
                                            />
                                            <div className="mb-2 mt-4 text-lg font-medium">
                                                CPlusPatch
                                            </div>
                                            <p className="text-sm leading-tight text-muted-foreground">
                                                Designed for simplicity. Built
                                                for performance. Made for you.
                                            </p>
                                        </Link>
                                    </NavigationMenuLink>
                                    {products.map((product) => (
                                        <li
                                            key={product.name}
                                            className="[&:nth-child(2n)]:col-start-2 [&:nth-child(2n+1)]:col-start-3"
                                        >
                                            <ProductItem {...product} />
                                        </li>
                                    ))}
                                </ul>
                            </NavigationMenuContent>
                        </NavigationMenuItem>
                        <NavigationMenuItem>
                            <Link
                                href="/blog"
                                legacyBehavior={true}
                                passHref={true}
                            >
                                <NavigationMenuLink className="text-sm font-semibold leading-6 text-foreground">
                                    Blog
                                </NavigationMenuLink>
                            </Link>
                        </NavigationMenuItem>
                        <NavigationMenuItem>
                            <Link
                                href="/contact"
                                legacyBehavior={true}
                                passHref={true}
                            >
                                <NavigationMenuLink className="text-sm font-semibold leading-6 text-foreground">
                                    Contact
                                </NavigationMenuLink>
                            </Link>
                        </NavigationMenuItem>
                    </NavigationMenuList>
                </NavigationMenu>
                <div className="hidden lg:flex lg:flex-1 lg:justify-end">
                    <Link
                        href="https://github.com/cpluspatch/web-landing"
                        target="_blank"
                        className="text-sm font-semibold group leading-6 text-foreground flex items-center"
                    >
                        Source Code
                        <AnimatedArrow />
                    </Link>
                </div>
            </nav>
        </header>
    );
};

/**
 * Mobile menu component
 */
const MobileMenu: FC<{
    isOpen: boolean;
    setIsOpen: (isOpen: boolean) => void;
    products: ProductItemProps[];
    children: ReactNode;
}> = ({ isOpen, setIsOpen, products, children }) => (
    <Drawer open={isOpen} onOpenChange={setIsOpen}>
        <DrawerTrigger asChild={true}>{children}</DrawerTrigger>
        <DrawerContent>
            <div className="max-w-xl w-full mx-auto">
                <DrawerHeader>
                    <DrawerTitle>
                        <Link
                            href="/"
                            className="px-2"
                            onClick={() => setIsOpen(false)}
                        >
                            <span className="sr-only">CPlusPatch</span>
                            <Image
                                className="h-8 w-auto"
                                src="/images/icons/logo.svg"
                                alt="CPlusPatch Logo"
                                width={229}
                                height={229}
                            />
                        </Link>
                    </DrawerTitle>
                </DrawerHeader>
                <div className="p-4">
                    <div className="flex flex-col gap-y-4">
                        <Accordion type="single" collapsible={true}>
                            <AccordionItem value="item-1">
                                <Button
                                    variant="outline"
                                    className="w-full"
                                    asChild={true}
                                >
                                    <AccordionTrigger>
                                        Projects
                                    </AccordionTrigger>
                                </Button>
                                <AccordionContent className="py-4">
                                    <ul className="space-y-2">
                                        {products.map((product) => (
                                            <li key={product.name}>
                                                <ProductItem
                                                    {...product}
                                                    onClick={() =>
                                                        setIsOpen(false)
                                                    }
                                                />
                                            </li>
                                        ))}
                                    </ul>
                                </AccordionContent>
                            </AccordionItem>
                        </Accordion>
                        <Link href="/blog" onClick={() => setIsOpen(false)}>
                            <Button variant="outline" className="w-full">
                                Blog
                            </Button>
                        </Link>
                        <Link href="/contact" onClick={() => setIsOpen(false)}>
                            <Button variant="outline" className="w-full">
                                Contact
                            </Button>
                        </Link>
                        <Link
                            href="https://github.com/cpluspatch/web-landing"
                            target="_blank"
                            onClick={() => setIsOpen(false)}
                        >
                            <Button variant="outline" className="w-full">
                                Source Code
                            </Button>
                        </Link>
                    </div>
                </div>
            </div>
        </DrawerContent>
    </Drawer>
);

// app/components/headers/Navbar.vue
<script setup lang="ts">
import {
    ChevronDown,
    ExternalLink,
    Globe,
    Menu,
    MessagesSquare,
    Network,
    Server,
    X,
} from "lucide-vue-next";
import { NuxtLink } from "#components";
import {
    NavigationMenu,
    NavigationMenuContent,
    NavigationMenuItem,
    NavigationMenuLink,
    NavigationMenuList,
    NavigationMenuTrigger,
    navigationMenuTriggerStyle,
} from "~/components/ui/navigation-menu";
import { Sheet, SheetContent, SheetTrigger } from "~/components/ui/sheet";
import { Button } from "../ui/button";
import {
    Collapsible,
    CollapsibleContent,
    CollapsibleTrigger,
} from "../ui/collapsible";

const projects = [
    {
        name: "Versia",
        description:
            "Highly standardized federation protocol that's easy to use and understand.",
        icon: Network,
        href: "https://versia.pub",
    },
    {
        name: "Versia Server",
        description:
            "Reference implementation of the Versia protocol. Fast, lightweight and configurable.",
        icon: Server,
        href: "https://github.com/versia-pub/server",
    },
    {
        name: "JoinMastodon",
        description:
            "A landing page for mastodon.de, a social media with no ads, no tracking, and no algorithms. Made with Nuxt.js and Tailwind CSS.",
        icon: Globe,
        href: "https://join-mastodon.de",
    },
    {
        name: "KitsuLife",
        description:
            "Website for the Kitsu service suite, showcasing features and the community for Kitsu.",
        icon: MessagesSquare,
        href: "https://kitsu.life",
    },
];

const open = ref(false);
</script>
<template>
    <NavigationMenu
        as="header"
        data-phys="true"
        class="z-10 backdrop-blur-lg fixed top-0 inset-x-0 max-w-full *:w-full"
    >
        <Sheet>
            <NavigationMenuList
                as="nav"
                class="max-w-7xl mx-auto w-full grid grid-cols-[auto_auto] lg:grid-cols-[1fr_repeat(3,auto)_1fr] gap-6 items-center justify-between p-4 lg:px-8"
            >
                <NavigationMenuItem class="mr-auto">
                    <NuxtLink
                        v-slot="{ isActive, href, navigate }"
                        to="/"
                        custom
                    >
                        <NavigationMenuLink
                            :active="isActive"
                            :href="href"
                            @click="navigate"
                        >
                            <span class="sr-only">CPlusPatch</span>
                            <nuxt-img
                                class="size-8"
                                src="/images/icons/logo.svg"
                                alt="CPlusPatch Logo"
                            />
                        </NavigationMenuLink>
                    </NuxtLink>
                </NavigationMenuItem>

                <NavigationMenuItem class="hidden lg:block">
                    <NavigationMenuTrigger>Projects</NavigationMenuTrigger>

                    <NavigationMenuContent>
                        <ul
                            class="grid grid-cols-2 xl:grid-cols-4 gap-4 w-screen max-w-xl xl:max-w-7xl"
                        >
                            <NavigationMenuLink
                                :href="item.href"
                                v-for="item in projects"
                                :key="item.name"
                                class="p-4 group flex flex-col gap-2"
                            >
                                <div class="mb-2">
                                    <component
                                        :is="item.icon"
                                        class="size-6 text-secondary-foreground"
                                    />
                                </div>
                                <h2
                                    class="font-semibold text-secondary-foreground"
                                >
                                    {{ item.name }}
                                </h2>
                                <p class="text-muted-foreground">
                                    {{ item.description }}
                                </p>
                            </NavigationMenuLink>
                        </ul>
                    </NavigationMenuContent>
                </NavigationMenuItem>

                <NavigationMenuItem class="hidden lg:block">
                    <NuxtLink
                        v-slot="{ isActive, href, navigate }"
                        to="/blog"
                        custom
                    >
                        <NavigationMenuLink
                            :active="isActive"
                            :href="href"
                            :class="navigationMenuTriggerStyle()"
                            @click="navigate"
                        >
                            Blog
                        </NavigationMenuLink>
                    </NuxtLink>
                </NavigationMenuItem>

                <NavigationMenuItem class="hidden lg:block">
                    <NuxtLink
                        v-slot="{ isActive, href, navigate }"
                        to="/contact"
                        custom
                    >
                        <NavigationMenuLink
                            :active="isActive"
                            :href="href"
                            :class="navigationMenuTriggerStyle()"
                            @click="navigate"
                        >
                            Contact
                        </NavigationMenuLink>
                    </NuxtLink>
                </NavigationMenuItem>

                <NavigationMenuItem class="ml-auto hidden lg:block">
                    <NuxtLink
                        v-slot="{ isActive, href, navigate }"
                        to="https://github.com/cpluspatch/web-landing"
                        external
                        custom
                    >
                        <NavigationMenuLink
                            :active="isActive"
                            :href="href"
                            :class="navigationMenuTriggerStyle()"
                            @click="navigate"
                        >
                            Source Code
                            <ExternalLink class="size-4" />
                        </NavigationMenuLink>
                    </NuxtLink>
                </NavigationMenuItem>

                <SheetTrigger as-child>
                    <Button
                        class="lg:hidden"
                        size="icon"
                        variant="ghost"
                        @click="open = true"
                        aria-label="Open main menu"
                    >
                        <Menu class="size-6" />
                    </Button>
                </SheetTrigger>
            </NavigationMenuList>

            <SheetContent class="px-2 py-6 w-full max-w-md">
                <NuxtLink href="/" class="mx-4">
                    <span class="sr-only">CPlusPatch</span>
                    <nuxt-img
                        class="size-8"
                        src="/images/icons/logo.svg"
                        alt="CPlusPatch Logo"
                    />
                </NuxtLink>
                <NavigationMenuList
                    as="nav"
                    class="flex-col items-start *:w-full *:*:w-full *:*:justify-start"
                >
                    <Collapsible v-slot="{ open }">
                        <CollapsibleTrigger
                            :class="navigationMenuTriggerStyle()"
                        >
                            Projects
                            <ChevronDown
                                :class="[
                                open ? '-rotate-180' : '',
                                'size-5 duration-200 ml-auto',
                            ]"
                            />
                        </CollapsibleTrigger>
                        <CollapsibleContent>
                            <ul
                                class="flex flex-col ml-4 border-l border-border"
                            >
                                <NavigationMenuLink
                                    :href="item.href"
                                    v-for="item in projects"
                                    :key="item.name"
                                >
                                    {{ item.name }}
                                </NavigationMenuLink>
                            </ul>
                        </CollapsibleContent>
                    </Collapsible>

                    <NavigationMenuItem>
                        <NuxtLink
                            v-slot="{ isActive, href, navigate }"
                            to="/blog"
                            custom
                        >
                            <NavigationMenuLink
                                :active="isActive"
                                :href="href"
                                :class="navigationMenuTriggerStyle()"
                                @click="navigate"
                            >
                                Blog
                            </NavigationMenuLink>
                        </NuxtLink>
                    </NavigationMenuItem>

                    <NavigationMenuItem>
                        <NuxtLink
                            v-slot="{ isActive, href, navigate }"
                            to="/contact"
                            custom
                        >
                            <NavigationMenuLink
                                :active="isActive"
                                :href="href"
                                :class="navigationMenuTriggerStyle()"
                                @click="navigate"
                            >
                                Contact
                            </NavigationMenuLink>
                        </NuxtLink>
                    </NavigationMenuItem>

                    <NavigationMenuItem>
                        <NuxtLink
                            v-slot="{ isActive, href, navigate }"
                            to="https://github.com/cpluspatch/web-landing"
                            external
                            custom
                        >
                            <NavigationMenuLink
                                :active="isActive"
                                :href="href"
                                :class="navigationMenuTriggerStyle()"
                                @click="navigate"
                            >
                                Source Code
                                <ExternalLink class="size-4" />
                            </NavigationMenuLink>
                        </NuxtLink>
                    </NavigationMenuItem>
                </NavigationMenuList>
            </SheetContent>
        </Sheet>
    </NavigationMenu>
</template>
